name: surface-runoff-susceptibility-model

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11

  - geopandas
  - pandas
  - matplotlib
   - numpy<2.4

  - hvplot
  - holoviews
  - geoviews
  - cartopy

  - earthaccess

  - rioxarray
  - xarray
  - xarray-spatial

  - pysheds
  - rasterio

  - jupyterlab
  - notebook

  - pip
  - pip:
      - scikit-fuzzy